# configuracao do bd
quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = postgres
quarkus.datasource.password = m@rya!@#
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/ecommerce_db

%dev.quarkus.hibernate-orm.database.generation=drop-and-create

# desabilitar o docker 
quarkus.devservices.enabled=false

quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.bind-parameters=true